package com.elearning.backend.dto;

import com.elearning.backend.model.Question; // Assuming you imported the Question Entity
import lombok.Data; // Provides all getters/setters/toString/hashCode/equals
import lombok.NoArgsConstructor; // Provides the default constructor

import java.time.LocalDate;

@Data
@NoArgsConstructor
public class QuestionDTO {

    private Long id;
    private int questionIndex; // <-- This field MUST be included in the DTO
    private String questionText;
    private String optionA;
    private String optionB;
    private String optionC;
    private String optionD;
    private String correctAnswer;

    private Long testId;
    private String testTitle;
    private LocalDate testDate;

    // 🧱 Custom Constructor to map Question Entity → DTO
    public QuestionDTO(Question q) {

        // 1. Map core Question fields
        this.id = q.getId();
        // FIX: The field you were missing in the response earlier
        this.questionIndex = q.getQuestionIndex();

        this.questionText = q.getQuestionText();
        this.optionA = q.getOptionA();
        this.optionB = q.getOptionB();
        this.optionC = q.getOptionC();
        this.optionD = q.getOptionD();
        this.correctAnswer = q.getCorrectAnswer();

        // 2. Map Test details
        if (q.getTest() != null) {
            this.testId = q.getTest().getId();
            this.testTitle = q.getTest().getTitle();
            this.testDate = q.getTest().getDate();
        }
    }
}
// NOTE: All the explicit public getters and setters from your original code
// are now generated by the @Data annotation.